//defining the student data set

var students = [
  {
  number: 'Jack',
  track: 'iOS',
  achievements: 7,
  points: 340
  },
  {
  name: 'Jack',
  track: 'Web Design',
  achievements: 4,
  points: 350
  },
  {
  name: 'Adam',
  track: 'Front End Development',
  achievements: 2,
  points: 130
  },
  {
  name: 'Ben',
  track: 'JavaScript',
  achievements: 9,
  points: 950
  },
  {
  name: 'Holly',
  track: 'Python',
  achievements: 12,
  points: 256
  },
  {
  name: 'Holly',
  track: 'Python',
  achievements: 12,
  points: 256
  },
  {
  name: 'Harry',
  track: 'Python',
  achievements: 12,
  points: 256
  }
];

var travelers = [

{ Passenger : 1 , StartStn  : " Archway " , JourneyDuration : 0.38  },
{ Passenger : 2 , StartStn  : " Baker Street  " , JourneyDuration : 0.43  },
{ Passenger : 3 , StartStn  : " Baker Street  " , JourneyDuration : 1.17  },
{ Passenger : 4 , StartStn  : " Baker Street  " , JourneyDuration : 0.37  },
{ Passenger : 5 , StartStn  : " Baker Street  " , JourneyDuration : 0.30  },
{ Passenger : 6 , StartStn  : " Balham  " , JourneyDuration : 0.60  },
{ Passenger : 7 , StartStn  : " Bank  " , JourneyDuration : 0.25  },
{ Passenger : 8 , StartStn  : " Bank  " , JourneyDuration : 0.18  },
{ Passenger : 9 , StartStn  : " Barons Court  " , JourneyDuration : 0.57  },
{ Passenger : 10  , StartStn  : " Belsize Park  " , JourneyDuration : 0.30  },
{ Passenger : 11  , StartStn  : " Belsize Park  " , JourneyDuration : 0.32  },
{ Passenger : 12  , StartStn  : " Belsize Park  " , JourneyDuration : 0.35  },
{ Passenger : 13  , StartStn  : " Bermondsey  " , JourneyDuration : 0.33  },
{ Passenger : 14  , StartStn  : " Bond Street " , JourneyDuration : 0.43  },
{ Passenger : 15  , StartStn  : " Bond Street " , JourneyDuration : 0.32  },
{ Passenger : 16  , StartStn  : " Bond Street " , JourneyDuration : 0.47  },
{ Passenger : 17  , StartStn  : " Borough " , JourneyDuration : 0.27  },
{ Passenger : 18  , StartStn  : " Borough " , JourneyDuration : 0.33  },
{ Passenger : 19  , StartStn  : " Borough " , JourneyDuration : 0.28  },
{ Passenger : 20  , StartStn  : " Bounds Green  " , JourneyDuration : 0.58  },
{ Passenger : 21  , StartStn  : " Brixton " , JourneyDuration : 0.45  },
{ Passenger : 22  , StartStn  : " Brixton " , JourneyDuration : 0.52  },
{ Passenger : 23  , StartStn  : " Burnt Oak " , JourneyDuration : 0.63  },
{ Passenger : 24  , StartStn  : " Camden Town " , JourneyDuration : 0.30  },
{ Passenger : 25  , StartStn  : " Canary Wharf  " , JourneyDuration : 0.52  },
{ Passenger : 26  , StartStn  : " Canary Wharf  " , JourneyDuration : 0.48  },
{ Passenger : 27  , StartStn  : " Canary Wharf  " , JourneyDuration : 0.45  },
{ Passenger : 28  , StartStn  : " Canary Wharf  " , JourneyDuration : 0.45  },
{ Passenger : 29  , StartStn  : " Chancery Lane " , JourneyDuration : 0.53  },
{ Passenger : 30  , StartStn  : " Colindale " , JourneyDuration : 0.63  },
{ Passenger : 31  , StartStn  : " Earls Court " , JourneyDuration : 0.55  },
{ Passenger : 32  , StartStn  : " East Acton  " , JourneyDuration : 0.63  },
{ Passenger : 33  , StartStn  : " East Finchley " , JourneyDuration : 0.47  },
{ Passenger : 34  , StartStn  : " East India  " , JourneyDuration : 0.57  },
{ Passenger : 35  , StartStn  : " Elephant & Castle " , JourneyDuration : 0.30  },
{ Passenger : 36  , StartStn  : " Elephant & Castle " , JourneyDuration : 0.33  },
{ Passenger : 37  , StartStn  : " Euston  " , JourneyDuration : 0.20  },
{ Passenger : 38  , StartStn  : " Euston  " , JourneyDuration : 0.18  },
{ Passenger : 39  , StartStn  : " Finchley Central  " , JourneyDuration : 0.63  },
{ Passenger : 40  , StartStn  : " Finchley Central  " , JourneyDuration : 0.63  },
{ Passenger : 41  , StartStn  : " Goodge Street " , JourneyDuration : 0.30  },
{ Passenger : 42  , StartStn  : " Great Portland St " , JourneyDuration : 0.28  },
{ Passenger : 43  , StartStn  : " Green Park  " , JourneyDuration : 0.33  },
{ Passenger : 44  , StartStn  : " Hammersmith D " , JourneyDuration : 0.57  },
{ Passenger : 45  , StartStn  : " Hammersmith D " , JourneyDuration : 0.60  },
{ Passenger : 46  , StartStn  : " Hampstead " , JourneyDuration : 0.47  },
{ Passenger : 47  , StartStn  : " Hampstead " , JourneyDuration : 0.43  },
{ Passenger : 48  , StartStn  : " Hendon Central  " , JourneyDuration : 0.52  },
{ Passenger : 50  , StartStn  : " Kennington  " , JourneyDuration : 0.42  },
{ Passenger : 51  , StartStn  : " Kentish Town  " , JourneyDuration : 0.33  },
{ Passenger : 52  , StartStn  : " Kentish Town  " , JourneyDuration : 0.30  },
{ Passenger : 53  , StartStn  : " Kilburn " , JourneyDuration : 0.48  },
{ Passenger : 54  , StartStn  : " Kings Cross T " , JourneyDuration : 0.20  },
{ Passenger : 55  , StartStn  : " Knightsbridge " , JourneyDuration : 0.52  },
{ Passenger : 56  , StartStn  : " Knightsbridge " , JourneyDuration : 0.40  },
{ Passenger : 57  , StartStn  : " Lambeth North " , JourneyDuration : 0.48  },
{ Passenger : 58  , StartStn  : " Leicester Square  " , JourneyDuration : 0.40  },
{ Passenger : 59  , StartStn  : " Leytonstone " , JourneyDuration : 0.48  },
{ Passenger : 60  , StartStn  : " Liverpool Street  " , JourneyDuration : 0.30  },
{ Passenger : 61  , StartStn  : " Liverpool Street  " , JourneyDuration : 0.27  },
{ Passenger : 62  , StartStn  : " London Bridge " , JourneyDuration : 0.23  },
{ Passenger : 63  , StartStn  : " London Bridge " , JourneyDuration : 0.23  },
{ Passenger : 64  , StartStn  : " London Bridge " , JourneyDuration : 0.22  },
{ Passenger : 65  , StartStn  : " London Bridge " , JourneyDuration : 0.25  },
{ Passenger : 66  , StartStn  : " London Bridge " , JourneyDuration : 0.28  },
{ Passenger : 67  , StartStn  : " London Bridge " , JourneyDuration : 0.25  },
{ Passenger : 68  , StartStn  : " London Bridge " , JourneyDuration : 0.28  },
{ Passenger : 69  , StartStn  : " London Bridge " , JourneyDuration : 0.25  },
{ Passenger : 70  , StartStn  : " London City Airport " , JourneyDuration : 0.72  },
{ Passenger : 71  , StartStn  : " London City Airport " , JourneyDuration : 0.75  },
{ Passenger : 72  , StartStn  : " Marble Arch " , JourneyDuration : 0.72  },
{ Passenger : 73  , StartStn  : " Mile End  " , JourneyDuration : 0.35  },
{ Passenger : 74  , StartStn  : " Moorgate  " , JourneyDuration : 0.17  },
{ Passenger : 75  , StartStn  : " Moorgate  " , JourneyDuration : 0.18  },
{ Passenger : 76  , StartStn  : " Moorgate  " , JourneyDuration : 0.22  },
{ Passenger : 77  , StartStn  : " Mornington Crescent " , JourneyDuration : 0.25  },
{ Passenger : 78  , StartStn  : " North Greenwich " , JourneyDuration : 0.60  },
{ Passenger : 79  , StartStn  : " Northfields " , JourneyDuration : 0.87  },
{ Passenger : 80  , StartStn  : " Notting Hill Gate " , JourneyDuration : 0.62  },
{ Passenger : 81  , StartStn  : " Notting Hill Gate " , JourneyDuration : 0.52  },
{ Passenger : 82  , StartStn  : " Oakwood " , JourneyDuration : 0.68  },
{ Passenger : 83  , StartStn  : " Old Street  " , JourneyDuration : 0.12  },
{ Passenger : 84  , StartStn  : " Old Street  " , JourneyDuration : 0.13  },
{ Passenger : 85  , StartStn  : " Old Street  " , JourneyDuration : 0.17  },
{ Passenger : 86  , StartStn  : " Old Street  " , JourneyDuration : 0.22  },
{ Passenger : 87  , StartStn  : " Oxford Circus " , JourneyDuration : 0.40  },
{ Passenger : 88  , StartStn  : " Oxford Circus " , JourneyDuration : 0.27  },
{ Passenger : 89  , StartStn  : " Paddington  " , JourneyDuration : 0.48  },
{ Passenger : 90  , StartStn  : " Paddington  " , JourneyDuration : 0.48  },
{ Passenger : 91  , StartStn  : " Paddington FGW  " , JourneyDuration : 0.47  },
{ Passenger : 92  , StartStn  : " Paddington FGW  " , JourneyDuration : 0.43  },
{ Passenger : 93  , StartStn  : " Park Royal  " , JourneyDuration : 0.87  },
{ Passenger : 94  , StartStn  : " Piccadilly Circus " , JourneyDuration : 0.42  },
{ Passenger : 95  , StartStn  : " Pimlico " , JourneyDuration : 0.38  },
{ Passenger : 96  , StartStn  : " Pontoon Dock  " , JourneyDuration : 0.77  },
{ Passenger : 97  , StartStn  : " Prince Regent " , JourneyDuration : 0.80  },
{ Passenger : 98  , StartStn  : " Queensway " , JourneyDuration : 0.53  },
{ Passenger : 99  , StartStn  : " Shadwell DLR  " , JourneyDuration : 0.30  },
{ Passenger : 100 , StartStn  : " South Quay  " , JourneyDuration : 0.57  },
{ Passenger : 101 , StartStn  : " South Quay  " , JourneyDuration : 0.53  },
{ Passenger : 102 , StartStn  : " South Quay  " , JourneyDuration : 0.77  },
{ Passenger : 103 , StartStn  : " St Pauls  " , JourneyDuration : 0.60  },
{ Passenger : 104 , StartStn  : " Stockwell " , JourneyDuration : 0.42  },
{ Passenger : 105 , StartStn  : " Stockwell " , JourneyDuration : 0.45  },
{ Passenger : 106 , StartStn  : " Tottenham Court Rd  " , JourneyDuration : 0.35  },
{ Passenger : 107 , StartStn  : " Tottenham Court Rd  " , JourneyDuration : 0.48  },
{ Passenger : 108 , StartStn  : " Vauxhall  " , JourneyDuration : 0.42  },
{ Passenger : 109 , StartStn  : " Victoria  " , JourneyDuration : 0.35  },
{ Passenger : 110 , StartStn  : " Victoria  " , JourneyDuration : 0.40  },
{ Passenger : 111 , StartStn  : " Victoria  " , JourneyDuration : 0.37  },
{ Passenger : 112 , StartStn  : " Victoria  " , JourneyDuration : 0.33  },
{ Passenger : 113 , StartStn  : " Walthamstow Central " , JourneyDuration : 0.55  },
{ Passenger : 114 , StartStn  : " Waterloo  " , JourneyDuration : 0.38  },
{ Passenger : 115 , StartStn  : " Westferry " , JourneyDuration : 0.40  },
{ Passenger : 116 , StartStn  : " Westminster " , JourneyDuration : 0.47  }
];

